"""followers

Revision ID: 953fac785baf
Revises: 6c00843e6410
Create Date: 2021-10-05 14:42:24.367707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953fac785baf'
down_revision = '6c00843e6410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
